// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: proto/scorer/v1/scorer.proto

package scorerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scorer_Score_FullMethodName = "/fluxa.scorer.v1.Scorer/Score"
)

// ScorerClient is the client API for Scorer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Scorer serves the ONNX fraud model. Called by fraud.Engine after rules,
// best-effort (fail-open): any error/timeout falls back to rules-only.
type ScorerClient interface {
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type scorerClient struct {
	cc grpc.ClientConnInterface
}

func NewScorerClient(cc grpc.ClientConnInterface) ScorerClient {
	return &scorerClient{cc}
}

func (c *scorerClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, Scorer_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScorerServer is the server API for Scorer service.
// All implementations must embed UnimplementedScorerServer
// for forward compatibility.
//
// Scorer serves the ONNX fraud model. Called by fraud.Engine after rules,
// best-effort (fail-open): any error/timeout falls back to rules-only.
type ScorerServer interface {
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	mustEmbedUnimplementedScorerServer()
}

// UnimplementedScorerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScorerServer struct{}

func (UnimplementedScorerServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedScorerServer) mustEmbedUnimplementedScorerServer() {}
func (UnimplementedScorerServer) testEmbeddedByValue()                {}

// UnsafeScorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScorerServer will
// result in compilation errors.
type UnsafeScorerServer interface {
	mustEmbedUnimplementedScorerServer()
}

func RegisterScorerServer(s grpc.ServiceRegistrar, srv ScorerServer) {
	// If the following call pancis, it indicates UnimplementedScorerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scorer_ServiceDesc, srv)
}

func _Scorer_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScorerServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scorer_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScorerServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scorer_ServiceDesc is the grpc.ServiceDesc for Scorer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scorer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fluxa.scorer.v1.Scorer",
	HandlerType: (*ScorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _Scorer_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scorer/v1/scorer.proto",
}
